### ISSUE TITLE
Missing directory "calibration" cited in Readme.MD

### ISSUE THREAD

**Issue by electro-logic** [PanderMusubi/umik-1#1]
Missing directory "calibration" with the script make-graph.sh

**Comment by PanderMusubi** [comment]
Thanks, fixing this now.

**Comment by PanderMusubi** [comment]
@electro-logic Any specific serial numbers your are interested in? I will support them as there is only limited space here.

**Comment by electro-logic** [comment]
Hello, 

I'm interested in creating a script to correct an audio file given the calibration file, or to directly record a calibrated audio file. Is this project already doing this?

Attached my calibration

[7100526.txt](https://github.com/PanderMusubi/umik-1/files/8659504/7100526.txt)
[7100526_90deg.txt](https://github.com/PanderMusubi/umik-1/files/8659505/7100526_90deg.txt)

**Comment by PanderMusubi** [comment]
Yes, wait for the next commits I push

**Comment by PanderMusubi** [comment]
@electro-logic your files are here https://github.com/PanderMusubi/umik-1/tree/master/generated Enjoy and let me know if you need something else.

**Comment by electro-logic** [comment]
Thanks a lot.

Some suggestions:
- Some instructions or clues how to use XML files with Audacity
- ZIP files in the calibration folder by serial number, should be more manageable

**Comment by PanderMusubi** [comment]
Thanks. See latest version.

**Comment by PanderMusubi** [comment]
Support Audacity has been restored. They evolved to another format for filters.

**Comment by electro-logic** [comment]
Hi, I tried to download 7100526.zip but XML files for audacity are missing, should I generate them with some script?

**Comment by PanderMusubi** [comment]
Zip script did not include the,. Now is fixed. Let me know if they work properly.
